logos_path:
  3: /home/andy/PycharmProjects/web_football/static/download/test (2).jpg
saving_link: /home/andy/PycharmProjects/web_football/static/result/result_202005081415.jpg
time_intervals:
  end: 0
  start: 0
video_path: /home/andy/PycharmProjects/web_football/static/download/test (3).JPG
